### ISSUE TITLE
were the scrapers removed?

### ISSUE THREAD

**Issue by chppppp** [BenBrostoff/draftfast#125]
It's been a while since I've looked at this repo and a lot has changed!! The last time I pulled this project was back in 12/2016.

Were the scrapers removed?

**Comment by BenBrostoff** [comment]
@chppppp Yes, Rotogrinders politely asked me to remove the code so I complied. This repo IMO is hugely improved since 2016; check out the README and the [example on repl.it](https://repl.it/@BenBrostoff/AllWarlikeDemoware). Also feel free to shoot me an e-mail with any questions on usage. The issues are getting kind of crowded since there are big plans in 2019 for more improvements 👍
