### ISSUE TITLE
[Request]: Injest JSON

### ISSUE THREAD

**Issue by robotfactory** [BenBrostoff/draftfast#134]
It would be helpful to be able to injest a player list from a json file or json string object, similar to how .csv can be injested.

**Comment by sharkiteuthis** [comment]
agree. i'll make an issue and assign it to myself

**Comment by BenBrostoff** [comment]
I'm going to close this, although you're welcome @robotfactory or @sharkiteuthis to take this on in a fork. I don't think ingesting JSON should be a responsibility of this repo; even the CSV ingestion stuff is iffy. My hope moving forward is we can keep `draftfast` small - there's definitely a lot of bloat already from just not having a good idea of where this would end up. I see the responsibilities of this library as:

- Running optimizations
- Allowing the user to add customizations for optimizations (constraints, new rules, ex)
- Some diversification options for `run_multi`

How you construct the `player_pool` feels like a consumer and not library responsibility.

**Comment by chppppp** [comment]
Did anyone ever implement this?

**Comment by BenBrostoff** [comment]
No but I think I stand by that comment - Python has a `json` module and I think it's easy enough to do this outside the library. Worried about library bloat. I support CSVs because DraftKings and FanDuel provide them and over the last few years haven't changed the CSV format; for JSON, there's a question of what the JSON looks like and how to ingest it.

**Comment by chppppp** [comment]
Thanks for the fast reply Ben. I cant argue with your logic as the module is simple enough where the user can implement this stuff. I just love being lazy :) Thanks so much.
