### ISSUE TITLE
Matchup

### ISSUE THREAD

**Issue by jpmorgenthal** [BenBrostoff/draftfast#167]
What's the best way to incorporate opposing rank into the selection process? Thoughts?

**Comment by BenBrostoff** [comment]
@jpmorgenthal You could bake this into your projections (ex. use matchup to increase or decrease projection) or use `CustomRule` to mandate certain exposures to projections (ex. at minimum have four players in matchup). Since this isn't an Issue and more an opinion question, feel free to ping me on Slack if you want to discuss more.
