### ISSUE TITLE
If play a then play b

### ISSUE THREAD

**Issue by revdarr** [BenBrostoff/draftfast#185]
The test seems to only allow for multiple players on b.

For example:

```
CustomRule(
             group_a=lambda p: p.name=='Gary Payton II',
             group_b=lambda p: p.name=='Jayson Tatum' or p.name=='Jaylen Brown',
         )
```

works but always has both Tatum and Brown

but 

`CustomRule(
             group_a=lambda p: p.name=='Gary Payton II',
             group_b=lambda p: p.name=='Jayson Tatum'
         )`

Results in no solution found

**Comment by BenBrostoff** [comment]
@revdarr Can look into this - do you have a CSV with projections you can send here so I can replicate? Additionally, it's worth mentioning here on `CustomRule` the [default comparison is here](https://github.com/BenBrostoff/draftfast/blob/4b1a6cf67f3c6d29a26e7b6de4dd6113269245b8/draftfast/settings.py#L47-L48). You may need to override the default comparison such that ` solver_sum(g_a) == solver_sum(g_b)`. I can check this tomorrow and add a test with this exact condition (given player A is in the lineup, player B must be in the lineup and vice versa). This is definitely a very common use case so if there's a bug here I want to fix it ASAP.

**Comment by revdarr** [comment]
Thanks! Here's my CSV. 
[TestDK.csv](https://github.com/BenBrostoff/draftfast/files/7776133/TestDK.csv)

**Comment by BenBrostoff** [comment]
@revdarr This should be fixed by just changing the comparison function to `solver_sum(g_a) == solver_sum(g_b)`. I updated tests to show this scenario in https://github.com/BenBrostoff/draftfast/commit/bf209c80727dbb334a2fd4c8e9ea7501aadbdce9 . If you use this rule, my testing shows:

- A and B are guaranteed to be in the same lineup if one of them is in the optimized lineup
- Otherwise, neither will be in the lineup

**Comment by BenBrostoff** [comment]
Closing this issue as I think the test I added proves this works as expected.
